set_property SRC_FILE_INFO {cfile:C:/myfpga/at7_ex01/at7.srcs/constrs_1/new/at7.xdc rfile:../../../at7.srcs/constrs_1/new/at7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N11 [get_ports sys_clk_i]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T2 [get_ports ext_rst_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {beep}]
